### ISSUE TITLE
Show my tasks in 'Mine'

### ISSUE THREAD

**Issue by ankushdharkar** [Real-Dev-Squad/website-status#45] opened 2021-01-12 02:38 UTC
https://status.realdevsquad.com/mine should list all of the user's tasks 

## API Contracts
https://github.com/Real-Dev-Squad/website-api-contracts/tree/main/tasks

**Comment by saxenaaman628** [comment] 2021-02-19 04:15
Can I take this task

**Comment by whyDontI** [comment] 2021-04-14 14:18
> This might not be a Front-End only task, this might include some API fix from the Back-End

Even though the PR Is merged, seems like there is something wrong.
Can someone pick this up and perform a Root Cause Analysis and try to fix it?

We at least need to show the proper error message.
Ideally, the below error message should never appear on the screen.  


![Screenshot from 2021-04-14 19-45-44](https://user-images.githubusercontent.com/26569942/114725429-1cc19c00-9d5a-11eb-84b3-306e5c1f8607.png)

**Comment by saxenaaman628** [comment] 2021-04-14 14:46
I am working on this

**Comment by whyDontI** [comment] 2021-04-19 18:49
![Screenshot from 2021-04-19 23-44-59](https://user-images.githubusercontent.com/26569942/115287537-06f31300-a16e-11eb-8e7c-3ed6775a7cc1.png)

**Closed** 2021-04-24 12:17 UTC
